homeassistant:
  # Name of the location where Home Assistant is running
  name: Hemma
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
#  customize: !include customize.yaml

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 100
    icon: mdi:home
    
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 100
    icon: mdi:worker

#switch: !include switch.yaml
light: !include light.yaml
automation: !include_dir_merge_list automations/
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
cloud: !include alexa.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

# Update custom cards in lovelace
# https://github.com/custom-components/custom_updater
custom_updater:
  hide_sensor: true
  track:
    - cards
    - components
    - python_scripts
  card_urls: 
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

webhook:
 
zigbee2mqtt_networkmap:
 
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html?engine=circo '
    icon: 'mdi:graphql'
  nodered:
    title: 'Node-RED'
    icon: mdi:shuffle-variant
    url: http://hallon.local:1880

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

# Enables configuration UI
config:

person:

system_health:

discovery:
  ignore:
    - apple_tv
    - logitech_mediaserver
    - plex_mediaserver

mqtt:
  discovery: true
  broker: mqtt://192.168.0.62:1883
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

zwave:
  usb_path: /dev/ttyACM0

tradfri:
  host: 192.168.0.39
  allow_tradfri_groups: true

recorder:
  purge_keep_days: 7
  db_url: !secret maria_db_hallon

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sensor
      - switch
    entities:
      - binary_sensor.white_motion_occupancy

logger:
  default: info
  logs:
    homeassistant.components.discovery: error
    homeassistant.components.http.view: error
    homeassistant.components.device_tracker.linksys_smart: warn
    homeassistant.components.websocket_api.http.connection: info
    homeassistant.components.mqtt: debug
    homeassistant.components.zwave.util: info
    openzwave: info
    libopenzwave: info
    pyhap.accessory_driver: info
    pyhap.characteristic: info
    pyhap.hap_server: error
    async_upnp_client.traffic: info
    coap: info
    pytradfri.api.aiocoap_api: info

#binary_sensor:
#  platform: rfxtrx
#  devices:
#    082003052f15000670:
#      name: Brand
#      fire_event: true 
#      device_class: smoke
#      off_delay:
#        minutes: 5
      
media_player:
  - platform: sonos
  - platform: samsungtv
    host: 192.168.0.20
    mac: "78:ab:bb:67:3a:27"
    name: TV Vardagsrum

# Text to speech
tts:
  - platform: google
    language: 'sv'

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet

#device_tracker:
#  - platform: linksys_smart
#    host: 192.168.0.1
#    track_new_devices: false

homekit:
  auto_start: false # Needed for zwave to wake up
  filter:
    exclude_domains:
      - automation
      - script
      - input_boolean
      - switch
      - scene
      - device_tracker
      - media_player
    exclude_entities:
      - sensor.ringvagen_temperature
      - light.fibaro_wall_dimmer_vardagsrum_myslampor
      - light.vardagsrum_mys
      - light.vardagsrum
      - light.gastrum
      - light.kok
      - light.hall
      - light.sovrum
      - light.flowers
      - light.cozy_dozy
      - light.cozy_dozy_zb
      - light.living_room_zb
      - light.guest_room_zb
      - light.guest_room_ikea
      - light.kitchen_zb
      - light.kitchen_ikea
      - light.kitchen_sink_ikea 
      - light.bedroom_ikea
      - light.tkb_dimmer_1
      - binary_sensor.brand
    include_entities:
      - script.cozy_dozy
      - scene.per_s_morning
      - scene.darkness
      - scene.cleaning
      - script.leaving_home

input_boolean:
  myslampor_vardagsrum:
  cozy_dozy:
  pers_morning:
  cleaning:
  tobbe_morning_alarm:
    name: Tobbe morgonlarm
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted


