- platform: group
  name: Vardagsrum mys
  entities:
    - light.kraftlampan
    - light.garbage_lamp
    - light.living_room_flower
    - light.hanglamporna
    - light.baslampan
    - light.living_room_window
    - light.plexi_lamp
    - light.tv_banken
- platform: group
  name: Vardagsrum
  entities:
    - light.vardagsrum_mys
    - light.fibaro_wall_dimmer_vardagsrum_taklampa
- platform: group
  name: Gästrum
  entities:
    - light.gastbollen
    - light.gastbokhyllan
    - light.gastsoffan
    - light.guest_sideboard
    - light.guest_window # Lilla bollen...
- platform: group
  name: Kök
  entities:
    - light.koksbank
    - light.kitchen_sling
    - light.butler_lamp
    - light.koksstjarnan
    - light.kitchen_ceiling
    - light.kitchen_window
- platform: group
  name: Hall
  entities:
    - light.hallbyran
- platform: group
  name: Sovrum
  entities:
    - light.turbanen
    - light.sanglamporna
- platform: group
  name: Flowers
  entities:
    - light.hallblomma
    - light.koksblomman
- platform: switch
  name: Vardagsstjärnan
  entity_id: switch.nexa_remote_31
- platform: switch
  name: Kitchen sling
  entity_id: switch.kitchen_sling
- platform: switch
  name: Kitchen window
  entity_id: switch.kitchen_window
- platform: switch
  name: Hallbyrån
  entity_id: switch.telldus_plugin_switch_1
- platform: switch
  name: TV-Bänken
  entity_id: switch.telldus_plugin_switch_2
- platform: switch
  name: Gästbokhyllan
  entity_id: switch.gastbokhyllan
- platform: switch
  name: Gästsoffan
  entity_id: switch.gastsoffan
- platform: switch
  name: Guest window
  entity_id: switch.guest_window
- platform: switch
  name: Turbanen
  entity_id: switch.turbanen    
- platform: switch
  name: Sänglamporna
  entity_id: switch.sanglamporna    
- platform: switch
  name: Balkongen
  entity_id: switch.nexa_sovrum_3    
- platform: switch
  name: Julgranen
  entity_id: switch.nexa_vrum_2