  # - platform: yr
#   monitored_conditions:
#     - temperature
#     - symbol
# - platform: darksky
#   api_key: !secret darksky
#   monitored_conditions:
#     - temperature
#     - humidity
#     - precip_probability
#     - precip_intensity
#     - wind_speed
#     - pressure
#     - wind_bearing
#     - apparent_temperature
#     - icon
#- platform: rfxtrx                                                        
#  automatic_add: false 
#  devices:
#    0a520902a70000f2260279:
#      name: Gästrum
#      data_type:
#        - Humidity
#        - Temperature
#    08500700a800001379:
#      name: Ringvägen
#    0a520902870000ed140279:
#      name: Kök
#      data_type:
#        - Humidity
#        - Temperature
#    08500701880000ec79:
#      name: Gården
#    0a520905970000e3140279:
#      name: Sovrum
#      data_type:
#        - Humidity
#        - Temperature
#    0a520915b70000e2140269:
#      name: Vardagsrum
#      data_type:
#        - Humidity
#        - Temperature

- platform: template
  sensors:
    sovrum_temp_batt:
      friendly_name: "Sovrum tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.sovrum_temperature
      value_template: "{{ states.sensor.sovrum_temperature.attributes['Battery numeric']*10 }}"
    kok_temp_batt:
      friendly_name: "Kök tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.kok_temperature
      value_template: "{{ states.sensor.kok_temperature.attributes['Battery numeric']*10 }}"
    vardagsrum_temp_batt:
      friendly_name: "Vardagsrum tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.vardagsrum_temperature
      value_template: "{{ states.sensor.vardagsrum_temperature.attributes['Battery numeric']*10 }}"
    perryberry_battery:
      friendly_name: "Perry Berry"
      unit_of_measurement: '%'
      entity_id:
        - zwave.perry_berry
      value_template: "{{ states.zwave.perry_berry.attributes['battery_level']}}"
    softgreen_battery:
      friendly_name: "Soft Green"
      unit_of_measurement: '%'
      entity_id:
        - zwave.soft_green
      value_template: "{{ states.zwave.soft_green.attributes['battery_level']}}"

- platform: sql             
  db_url: mysql://hallon:rh5ny6@192.168.0.23/hallon
  icon: mdi:database
  queries:
   - name: Hallon DB size
     query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="hallon" GROUP BY table_schema;'
     column: 'value'
     unit_of_measurement: MB

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: mqtt
  name: Gården temperatur
  state_topic: "homeassistant/sensor/garden_thermometer"
  icon: mdi:thermometer
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: '°C'

- platform: mqtt
  name: Kitchen temperature
  state_topic: "homeassistant/sensor/kitchen_thermometer"
  icon: mdi:thermometer
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: '°C'

- platform: mqtt
  name: Kitchen humidity
  state_topic: "homeassistant/sensor/kitchen_thermometer"
  icon: mdi:water
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: '%'

- platform: mqtt
  name: Kitchen thermometer battery
  state_topic: "homeassistant/sensor/kitchen_thermometer"
  icon: mdi:battery-70
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: '%'

- platform: mqtt
  name: Living room temperature
  state_topic: "homeassistant/sensor/living_room_thermometer"
  icon: mdi:thermometer
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: '°C'

- platform: mqtt
  name: Living room humidity
  state_topic: "homeassistant/sensor/living_room_thermometer"
  icon: mdi:water
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: '%'

- platform: mqtt
  name: Living room thermometer battery
  state_topic: "homeassistant/sensor/living_room_thermometer"
  icon: mdi:battery-70
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: '%'  
        
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_use
