# - platform: yr
#   monitored_conditions:
#     - temperature
#     - symbol
# - platform: darksky
#   api_key: !secret darksky
#   monitored_conditions:
#     - temperature
#     - humidity
#     - precip_probability
#     - precip_intensity
#     - wind_speed
#     - pressure
#     - wind_bearing
#     - apparent_temperature
#     - icon
- platform: rfxtrx                                                        
  automatic_add: false 
  devices:
    0a520902a70000f2260279:
      name: Gästrum
      data_type:
        - Humidity
        - Temperature
    08500700a800001379:
      name: Ringvägen
    0a520902870000ed140279:
      name: Kök
      data_type:
        - Humidity
        - Temperature
    08500701880000ec79:
      name: Gården
    0a520905970000e3140279:
      name: Sovrum
      data_type:
        - Humidity
        - Temperature
    0a520915b70000e2140269:
      name: Vardagsrum
      data_type:
        - Humidity
        - Temperature

- platform: template
  sensors:
    gastrum_temp_batt:
      friendly_name: "Gästrum tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.gastrum_temperature
      value_template: "{{ states.sensor.ringvagen_temperature.attributes['Battery numeric']*10 }}"
    sovrum_temp_batt:
      friendly_name: "Sovrum tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.sovrum_temperature
      value_template: "{{ states.sensor.sovrum_temperature.attributes['Battery numeric']*10 }}"
    kok_temp_batt:
      friendly_name: "Kök tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.kok_temperature
      value_template: "{{ states.sensor.kok_temperature.attributes['Battery numeric']*10 }}"
    vardagsrum_temp_batt:
      friendly_name: "Vardagsrum tempbatteri"
      unit_of_measurement: '%'
      entity_id:
        - sensor.vardagsrum_temperature
      value_template: "{{ states.sensor.vardagsrum_temperature.attributes['Battery numeric']*10 }}"
    perryberry_battery:
      friendly_name: "Perry Berry"
      unit_of_measurement: '%'
      entity_id:
        - zwave.perry_berry
      value_template: "{{ states.zwave.perry_berry.attributes['battery_level']}}"
    softgreen_battery:
      friendly_name: "Soft Green"
      unit_of_measurement: '%'
      entity_id:
        - zwave.soft_green
      value_template: "{{ states.zwave.soft_green.attributes['battery_level']}}"
    white_button_1_battery:
      unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_1
      value_template: "{{ states.sensor.white_button_1.attributes['battery']}}"
    white_button_1_linkquality:
      #unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_1
      value_template: "{{ states.sensor.white_button_1.attributes['linkquality']}}"
    white_button_2_battery:
      unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_2
      value_template: "{{ states.sensor.white_button_2.attributes['battery']}}"
    white_button_2_linkquality:
      #unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_2
      value_template: "{{ states.sensor.white_button_2.attributes['linkquality']}}"
    white_button_3_battery:
      unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_3
      value_template: "{{ states.sensor.white_button_3.attributes['battery']}}"
    white_button_3_linkquality:
      #unit_of_measurement: '%'
      entity_id:
        - sensor.white_button_3
      value_template: "{{ states.sensor.white_button_3.attributes['linkquality']}}"
    white_temp_1_battery:
      unit_of_measurement: '%'
      entity_id:
        - sensor.white_temp_1_temp
      value_template: "{{ states.sensor.white_temp_1_temp.attributes['battery']}}"
    white_temp_1_linkquality:
      #unit_of_measurement: '%'
      entity_id:
        - sensor.white_temp_1_temp
      value_template: "{{ states.sensor.white_temp_1_temp.attributes['linkquality']}}"
#    weather_aggregation:
#      friendly_name: "Väder"
#      value_template: "{{ states.sensor.yr_temperature.state }}"
#      entity_picture_template: "{{ states.sensor.yr_symbol.attributes['entity_picture']}}"
#      unit_of_measurement: '°C'
#      entity_id:
#        - sensor.yr_temperature
#        - sensor.yr_symbol

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
        
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_use

- platform: speedtest
  minute: 30
  hour:
    - 0
  monitored_conditions:
    - ping
    - download
    - upload
