- platform: template
  sensors:
    perryberry_battery:
      friendly_name: "Perry Berry"
      unit_of_measurement: '%'
      entity_id:
        - zwave.perry_berry
      value_template: "{{ states.zwave.perry_berry.attributes['battery_level']}}"
    softgreen_battery:
      friendly_name: "Soft Green"
      unit_of_measurement: '%'
      entity_id:
        - zwave.soft_green
      value_template: "{{ states.zwave.soft_green.attributes['battery_level']}}"

- platform: sql             
  db_url: !secret maria_db_hallon
  queries:
   - name: Hallon DB size
     query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="hallon" GROUP BY table_schema;'
     column: 'value'
     unit_of_measurement: MB

- platform: sql             
  db_url: !secret maria_db_lingon
  queries:
   - name: Lingon DB size
     query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="lingon" GROUP BY table_schema;'
     column: 'value'
     unit_of_measurement: MB     

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
        
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_use
