- platform: rfxtrx
  automatic_add: true
  devices:
    #################################
    # Liten nexafjärr märkt "Gästrum"
    #################################
    0b11004d00aca2fe01010f70:
      name: nexa_gastrum_1
      fire_event: true
    
    #################################
    # Liten nexafjärr märkt "Kök"
    #################################
    0b11003c00b73f2e01000070:
      name: nexa_kok_1
      fire_event: true
    0b11004000b73f2e02010f70:
      name: nexa_kok_2
      fire_event: true
    0b11000500b73f2e03000070:
      name: nexa_kok_3
      fire_event: true
   ####################################
    # Inbyggda nexasändaren i köket
    ####################################
    0b110002016093ea02010f60:
      # name: Diskbänk
      name: Kitchen wall remote
   ####################################
    # Den vita fjärrkontrollen, läge IV
    ####################################
    0b11002c00a7d9920d010f70:
      name: nexa_remote_41
    
    ####################################
    # Lilla vit i sovrummet
    ####################################
    0b11000000e63cd601000070:
      name: nexa_sovrum_1
      fire_event: true
    0b11000200e63cd602000070:
      name: nexa_sovrum_2
      fire_event: true
    0b11000600e63cd603010f60: # Balkong
      name: nexa_sovrum_3
      fire_event: true
   ####################################
    # Den vita fjärrkontrollen, läge I
    ####################################
    0b11000300a7d99201030070:
      name: nexa_remote_11
      fire_event: true
    0b11009300a7d99202010f70:
      name: nexa_remote_12
      fire_event: true
    0b11009400a7d99203010f70:
      name: nexa_remote_13
      fire_event: true
    0b11000400a7d99204010f70:
      name: nexa_remote_14
      fire_event: true
    ####################################
    # Den vita fjärrkontrollen, läge II
    ####################################
    0b11001400a7d99205010f70:
      name: nexa_remote_21 # Gäststjärnan
      fire_event: true
    0b11001500a7d99206010f70:
      name: nexa_remote_22 # Taklampa hall.
      fire_event: true
    0b11001600a7d99207010f70:
      name: nexa_remote_23  # Skåpslingan
      fire_event: true
    # 0b11000d00a7d99208000060:
    #   name: nexa_remote_24 # Balkongen
    #   fire_event: true
   ####################################
    # Den vita fjärrkontrollen, läge II
    ####################################
    0b11002800a7d99209010f60:
      name: nexa_remote_31  # Vardagsstjärnan
      fire_event: true
    ####################################
    # Lilla vita, vrum, i ordning
    ####################################
#    0b1100030080832e01010f60:
#      name: Plexihörnan
#      fire_event: true
    0b11008b0080832e02010f70:
      name: nexa_vrum_2
#   0b1100020080832e03010f70:
#     name: Fönsterlampa